# Generated by Django 2.2.12 on 2020-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(db_column='event_id', primary_key=True, serialize=False)),
                ('event_date', models.DateField(db_column='event_date')),
                ('begins', models.TimeField(db_column='begins')),
                ('ends', models.TimeField(db_column='ends')),
                ('multi_day_event', models.BooleanField(db_column='multi_day_event', default=0)),
                ('multi_day_ends_date', models.DateField(blank=True, db_column='multi_day_ends_date', null=True)),
                ('repeat', models.CharField(choices=[('N', 'Never'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], db_column='repeat', max_length=1)),
                ('location', models.CharField(db_column='location', max_length=180)),
                ('event_name', models.CharField(db_column='event_name', max_length=180)),
                ('description', models.TextField(db_column='description', max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
